>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()
>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented

>>> bg.integer_validator("", 10)

>>> bg.integer_validator(123, 10)

>>> bg.integer_validator("value", None)
Traceback (most recent call last):
...
TypeError: value must be an integer

>>> bg.integer_validator("value", True)
Traceback (most recent call last):
...
TypeError: value must be an integer

>>> bg.integer_validator("value", [1, 2, 3])
Traceback (most recent call last):
...
TypeError: value must be an integer

>>> bg.integer_validator("value", (1, 2, 3))
Traceback (most recent call last):
...
TypeError: value must be an integer

>>> bg.integer_validator("value", {1, 2, 3})
Traceback (most recent call last):
...
TypeError: value must be an integer

>>> bg.integer_validator("value", {"a": 1, "b": 2})
Traceback (most recent call last):
...
TypeError: value must be an integer

>>> bg.integer_validator("value", 1.5)
Traceback (most recent call last):
...
TypeError: value must be an integer

>>> bg.integer_validator("width", None)
Traceback (most recent call last):
...
TypeError: width must be an integer

>>> bg.integer_validator("name")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg.integer_validator("name", 1, 2)
Traceback (most recent call last):
...
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> bg.area(5)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 2 were given

>>> bg.area(5, 5)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 3 were given

>>> bg.integer_validator("age", -4)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

>>> bg.integer_validator("age", 0)
Traceback (most recent call last):
...
ValueError: age must be greater than 0

>>> bg.integer_validator("age", "4")
Traceback (most recent call last):
...
TypeError: age must be an integer